### ISSUE TITLE
create edabit issues

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#1]
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ]  Check for the problem and make sure it's doesn't exist in solution already
- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by rexdivakar** [comment]
Please assign me the task

**Comment by aayushi-droid** [comment]
@rexdivakar  Yes sure , This issue is open for all.

Task - Create issue from Edabit problem, make sure to avoid duplicate question. use template for making issue.
Best of Luck

**Comment by rexdivakar** [comment]
> @rexdivakar  Yes sure , This issue is open for all.
> 
> Task - Create issue from Edabit problem, make sure to avoid duplicate question. use template for making issue.
> Best of Luck

Is it fine can I raise the PR after Oct 1st so my PR gets considered for the Hacktoberfest

**Comment by aayushi-droid** [comment]
Make your PR after 1 October for HacktoberFest

**Comment by sreekesari-vangeepuram** [comment]
How can I make a PR for `primorial` problem?
