### ISSUE TITLE
Power Calculator

### ISSUE THREAD

**Issue by Gerald-Izuchukwu** [Py-Droid/Python-Thunder#113]
Create a function that takes voltage and current and returns the calculated power.
link: https://edabit.com/challenge/v5gc8FQkDEepkqpfp

**Comment by Gerald-Izuchukwu** [comment]
Can I please be assigned to this

**Comment by gittygupta** [comment]
Please assign this issue to me

**Comment by aayushi-droid** [comment]
Invalid PR, Created with assigned, Marking Invalid. It will not count for Hacktober now. @gittygupta

**Comment by Gerald-Izuchukwu** [comment]
please label my issue

**Comment by aayushi-droid** [comment]
Please Use Issue template for automate the Labeling process.
