### ISSUE TITLE
FizzBuzz Interview Question

### ISSUE THREAD

**Issue by xPolar** [Py-Droid/Python-Thunder#115]
Before jumping into PR first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes a number as an argument and returns `"Fizz"`, `"Buzz"` or `"FizzBuzz"`.
**Problem Link:**  https://edabit.com/challenge/WXqH9qvvGkmx4dMvp

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck.

**Comment by xPolar** [comment]
Please assign this to me!

**Comment by am401** [comment]
Hello there - is it possible to have this assigned to me in order to submit the solution?

**Comment by xPolar** [comment]
You're supposed to create your own issue for a challenge on Edabit, I created this one so It's assigned for me.

**Comment by am401** [comment]
Thank you for the clarification @xPolar 👍

**Comment by xPolar** [comment]
No problem!
