### ISSUE TITLE
Assign this Problem Statement: Convert Hours into Seconds 

### ISSUE THREAD

**Issue by sarsiz** [Py-Droid/Python-Thunder#118]
**Problem statement:Convert Hours into Seconds**
**Problem Link:https://edabit.com/challenge/nyeNvKWdDFKRAk4Da** 

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by typg93** [comment]
Can I take this one?

**Comment by sarsiz** [comment]
I am not the person who's supposed to assign this project and I've selected this problem statement for me from edabit challenge.
If you want to contribute, I suggest you to read there PR guideline first and then proceed.

**Comment by JHNLWHD** [comment]
Can I take this issue @sarsiz ?

**Comment by sarsiz** [comment]
@JHNLWHD Please see the above comment.

**Comment by JHNLWHD** [comment]
I see @sarsiz, thanks
