### ISSUE TITLE
Double Character Swap 

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#12]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function to replace all instances of character c1 with character c2 and vice versa.
**Problem Link:** https://edabit.com/challenge/mHRyhyazjCoze5jSL

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gokulrajanpillai** [comment]
Please assign me for this. Thanks

**Comment by aayushi-droid** [comment]
- [✓]  Task Assigned, Go Ahead
@gokulrajanpillai

**Comment by gokulrajanpillai** [comment]
can you add me as contributor to make the PR? I will make it only on Oct1

**Comment by AdeshChoudhar** [comment]
I would like to work on this.
