### ISSUE TITLE
Area of a Triangle 

### ISSUE THREAD

**Issue by varshatumburu** [Py-Droid/Python-Thunder#122]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that takes the base and height of a triangle and returns its area.
**Problem Link:** https://edabit.com/challenge/3CaszbdZYGN4otQD8 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by nishamehra** [comment]
@varshatumburu please assign this problem to me. i would like to contribute for this problem.

**Comment by prathmeshChaudhari05** [comment]
@varshatumburu Please assign this task to me.
