### ISSUE TITLE
The Farm Problem

### ISSUE THREAD

**Issue by tarundhiraj** [Py-Droid/Python-Thunder#129]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
Write a function that takes number of chickens, cows and pigs and returns total number of legs these animals have.
**Problem Link:** 
https://edabit.com/challenge/QzXtDnSZL6y4ZcEvT

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by tarundhiraj** [comment]
I would like to contribute. Please assign this issue to me.

**Comment by aswarth123** [comment]
I would like to solve this issue can you assign it to me?

**Comment by subhamagrawal7** [comment]
I would like to solve the issue. Could please assign it to me?? I am also ready to solve another issue if you have.

**Comment by aayushi-droid** [comment]
Duplicate issue, Issue created earlier and solved too.
