### ISSUE TITLE
List of Multiples

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#13]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes two numbers as arguments (num, length) and returns a list of multiples of num up to length.
**Problem Link:**  https://edabit.com/challenge/BuwHwPvt92yw574zB

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gokulrajanpillai** [comment]
I call dibs

**Comment by aayushi-droid** [comment]
- [✓]  Task Assigned
@gokulrajanpillai

**Comment by gokulrajanpillai** [comment]
@aayushi-droid  can you add me as contributor to make the PR?

**Comment by aayushi-droid** [comment]
@gokulrajanpillai  yes sure, I am inviting you in org, check your email.

Task - Create issue from Edabit problem, make sure to avoid duplicate question. use template for making issue.Assign people according to issues.
Best of Luck

**Comment by AdeshChoudhar** [comment]
I would like to work on this.
