### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by tarundhiraj** [Py-Droid/Python-Thunder#130]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** 
Create a function that converts Celcius to Fahrenheit and vice versa.
**Problem Link:** 
https://edabit.com/challenge/9CNJtMXaw2K5NwMLJ

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by tarundhiraj** [comment]
I would like to contribute to this issue. Please assign it to me. Thanks.

**Comment by subhamagrawal7** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by paramphy** [comment]
I would like to contribute to this issue. Please assign it to me.
