### ISSUE TITLE
Convert Minutes into Seconds

### ISSUE THREAD

**Issue by prathmeshChaudhari05** [Py-Droid/Python-Thunder#132]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement: Convert Minutes into Seconds
**Problem Link: https://edabit.com/challenge/FQyaaJx7orS7tiwz8 

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by prathmeshChaudhari05** [comment]
please assign this task to me.

**Comment by tanishqj2005** [comment]
please assign this task to me. Thanks!

**Comment by aayushi-droid** [comment]
duplicate issue, issue created earlier and solved too
