### ISSUE TITLE
Absolute Sum

### ISSUE THREAD

**Issue by subhamagrawal7** [Py-Droid/Python-Thunder#136]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
Take a list of integers (positive or negative or both) and return the sum of the absolute value of each element.
**Problem Link: https://edabit.com/challenge/5eHy5yapqz8kP94ih** 

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by subhamagrawal7** [comment]
I would like to contribute to this issue. Please assign it to me. Thanks.

**Comment by ymchandaliya** [comment]
@subhamagrawal7 I would like to contribute to this issue. Please assign it to me. Thanks

**Comment by suparna13** [comment]
I would like to contribute on this in very creative optimized python solution. Can you please assign it to me so that I can jump to code? Thank You.

**Comment by subhamagrawal7** [comment]
> @subhamagrawal7 I would like to contribute to this issue. Please assign it to me. Thanks

I cannot assign it to you.

**Comment by Hinal-Srivastava** [comment]
I am interested to contribute to this.
