### ISSUE TITLE
ASCII Charcode of Inverse Case Character

### ISSUE THREAD

**Issue by RAM-BHARATH** [Py-Droid/Python-Thunder#138]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
Find ASCII Charcode of Inverse Case Character
Create a function that takes a single character as an argument and returns the char code of its lowercased / uppercased counterpart.
**Problem Link:** 
https://edabit.com/challenge/QFXMcwaQZ8FTAuEtg
---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by RAM-BHARATH** [comment]
I would like to contribute to this.

**Comment by ymchandaliya** [comment]
I would like to contribute to this.

**Comment by ruthwik3690** [comment]
I can do this. Please let me in.

**Comment by Hinal-Srivastava** [comment]
Hi, I'd like to do this.

**Comment by aayushi-droid** [comment]
Thanks for messaging but priority will give to issue-author(who created the issue)
