### ISSUE TITLE
Smiley Faces :)

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#14]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** You will be given a string of characters containing only the three characters : ( ) :

Create a function returns a number based on the number of sad and smiley faces there are.

- The happy faces :) and (: are worth 1.
- The sad faces :( and ): are worth -1.

**Problem Link:** https://edabit.com/challenge/8qD23E6XRMaWhyJ5z

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by matheusqz** [comment]
@aayushi-droid Can I work on it?

**Comment by aayushi-droid** [comment]
- [✓]  Task Assigned, Go Ahead
@Matheusqz
