### ISSUE TITLE
Find the Odd Integer

### ISSUE THREAD

**Issue by sudesh1611** [Py-Droid/Python-Thunder#143]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes an array and finds the integer which appears an odd number of times.
**Problem Link:** https://edabit.com/challenge/9TcXrWEGH3DaCgPBs

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by sudesh1611** [comment]
@aayushi-droid Please assign this to me

**Comment by Manavi18** [comment]
I can implement this in python.

**Comment by sudesh1611** [comment]
@Manavi18 You can create your own issue with problem from [https://edabit.com/challenges](https://edabit.com/challenges)

**Comment by shin-iji** [comment]
@sudesh1611 can i try this issue?

**Comment by akash7301** [comment]
please assign.

**Comment by Koshal67** [comment]
Hello Developer
I am happy to resolve your issue . 
It's pretty easy . Just assign it to me .
Thanks 
github.com/Koshal67/

**Comment by himik-nainwal** [comment]
I did like to work on this please assign me. I recently completed python and completed 5 star in hackerrank. > Thanks

**Comment by aayushi-droid** [comment]
Thanks for messaging but priority will give to issue-author(who created the issue)

**Comment by aayushi-droid** [comment]
#158
