### ISSUE TITLE
Caesar's Cipher

### ISSUE THREAD

**Issue by sudesh1611** [Py-Droid/Python-Thunder#144]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Julius Caesar protected his confidential information by encrypting it using a cipher. Caesar's cipher (check Resources tab for more info) shifts each letter by a number of letters. If the shift takes you past the end of the alphabet, just rotate back to the front of the alphabet. In the case of a rotation by 3, w, x, y and z would map to z, a, b and c. Create a function that takes a string s (text to be encrypted) and an integer k (the rotation factor). It should return an encrypted string.
**Problem Link:** https://edabit.com/challenge/C45TKLcGxh8dnbgqM

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by sudesh1611** [comment]
@aayushi-droid Please assign this to me

**Comment by KuruvillaJacob02** [comment]
If this issue has not been assigned , it would be much appreciated if you would assign it to me

**Comment by sudesh1611** [comment]
@KuruvillaJacob02 You can create your own issue with problem from [https://edabit.com/challenges](https://edabit.com/challenges)

**Comment by KuruvillaJacob02** [comment]
Hello there, I've completed the code for ceasars cipher and checked the code on edabit and It passed the 4 tests, what should I do from this point onwards?

**Comment by aayushi-droid** [comment]
Thanks for messaging but priority will give to issue-author(who created the issue)

**Comment by aayushi-droid** [comment]
#158
