### ISSUE TITLE
Are the Sum of Digits in the Numbers Equal?

### ISSUE THREAD

**Issue by rishabgit** [Py-Droid/Python-Thunder#147]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
Create a function that takes two parameters and, if both parameters are strings, add them as if they were integers or if the two parameters are integers, concatenate them.
**Problem Link:** 
https://edabit.com/challenge/6dnhESWBcTMMF3gsa

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by rishabgit** [comment]
@aayushi-droid May I please work on this?

**Comment by snehagupta-4** [comment]
> Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add
> 
> **Problem statement:**
> Create a function that takes two parameters and, if both parameters are strings, add them as if they were integers or if the two parameters are integers, concatenate them.
> **Problem Link:**
> https://edabit.com/challenge/6dnhESWBcTMMF3gsa
> 
> Before submitting a PR please Check some details.Check Edabit for problem task
> 
> * [ ]  fileName formet should be in camelcase
>   example- returnTheNextNumber.py
> * [ ]   Add label for Problem
> * [ ]   In file there should be problem statement and link to probelm
>   example -
> 
> ```python
> '''
>     Probem Task : This program will add two numbers
>     Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
> '''
> */
> def main():
>     return a + b
> ```
> 
> This repository is vaild for HacktoberFest2020
> 
> Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
> Good Luck,

Hey @rishabmallick I'd like to work on this. Please assign it to me

**Comment by himik-nainwal** [comment]
I did like to work on this please assign me. I recently completed python and completed 5 star in hackerrank. > Thanks

**Comment by PritamSinghaRoy** [comment]
i would love to work on it plz assign this to me

**Comment by aayushi-droid** [comment]
@snehagupta-4 please create a new issue. green button on right upper corner
