### ISSUE TITLE
Simple OOP Calculator

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#15]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create methods for the Calculator class that can do the following:

- Add two numbers.
- Subtract two numbers.
- Multiply two numbers.
- Divide two numbers.

**Problem Link:** https://edabit.com/challenge/ta8GBizBNbRGo5iC6

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
Hey @aayushi-droid can you assign me  this issue

**Comment by aayushi-droid** [comment]
- [✓]  Task Assigned
@keshav304

**Comment by sudhir512kj** [comment]
Hello @aayushi-droid I would like to work on this.
