### ISSUE TITLE
Return the Remainder from Two Numbers

### ISSUE THREAD

**Issue by suparna13** [Py-Droid/Python-Thunder#151]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement: There is a single operator in Python, capable of providing the remainder of a division operation. Two numbers are passed as parameters. The first parameter divided by the second parameter will have a remainder, possibly zero. Return that value.
Problem Link: https://edabit.com/challenge/KWoj7kWiHRqJtG6S2

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by suparna13** [comment]
@aayushi-droid I would like to contribute to this issue. Please assign it to me. Thanks.

**Comment by shin-iji** [comment]
@suparna13 can i try this?

**Comment by himik-nainwal** [comment]
I would like to do this problem. Recently i have completed 5 star in hackerrank python practice . I can make it good. Thanks

**Comment by rajinderpalsingh2001** [comment]
Please assign the issue to me,I will surely meet your requirements.
