### ISSUE TITLE
Is the Number Less than or Equal to Zero

### ISSUE THREAD

**Issue by suparna13** [Py-Droid/Python-Thunder#153]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement: Create a function that takes a number as its only argument and returns true if it's less than or equal to zero, otherwise return false.
Problem Link: https://edabit.com/challenge/Rx2pkSA9dCmtwS8xt

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by suparna13** [comment]
@aayushi-droid I would like to contribute to this issue. Please assign it to me. Thanks.

**Comment by himik-nainwal** [comment]
I have just completed python with basics > please assign this to me...

**Comment by SUKANTHEN** [comment]
I would like to Do this ! Help me make my First PR !

**Comment by noemi3** [comment]
Hi! I would like to work on this issue. Thanks.

**Comment by Amrita211** [comment]
Hello @suparna13 I would like to work on this, please assign it to me.
