### ISSUE TITLE
Rearrange the Number

### ISSUE THREAD

**Issue by RitikaAg** [Py-Droid/Python-Thunder#159]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:Given a number, return the difference between the maximum and minimum numbers that can be formed when the digits are rearranged.**
**Problem Link:https://edabit.com/challenge/jwzAdBnJnBxCe4AXP** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by RitikaAg** [comment]
Please assign this to me

**Comment by KuruvillaJacob02** [comment]
Has this issue been assigned yet, If not it would be much appreciated if this issue is assigned to me

**Comment by tdserapio** [comment]
I would love to work on this task, and I have made a sufficient solution already. please assign me to this task. Thank you!
