### ISSUE TITLE
New Word Builder

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#16]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that builds a word from the scrambled letters contained in the first list. Use the second list to establish each position of the letters in the first list. Return a string from the unscrambled letters (that made-up the word).

**Problem Link:**  https://edabit.com/challenge/R5F99DeuhqYxbGyMM

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by matheusqz** [comment]
@aayushi-droid Can I work on it?

**Comment by aayushi-droid** [comment]
yes sure
- [✓]  Task assigned
@Matheusqz

**Comment by sudhir512kj** [comment]
Hello @aayushi-droid I would like to work on this.

**Comment by gittygupta** [comment]
Please assign this issue to me
