### ISSUE TITLE
Return the First Element in an Array

### ISSUE THREAD

**Issue by ghost** [Py-Droid/Python-Thunder#162]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement:Create a function that takes an array and returns the first element
Problem Link:https://edabit.com/challenge/QaApgtePE6QrCZ64o

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
Please assign me this issue

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid Please assign this task to me.Thanks!

**Comment by ghost** [comment]
@aayushi-droid Please assign me this task

**Comment by Renu-code** [comment]
@aayushi-droid can you please assign this issue to me

**Comment by noemi3** [comment]
Hi! I would like to work on this issue. Thanks.

**Comment by Raghibshams456** [comment]
please assign it to me...

**Comment by FarhanMuftiHilmy** [comment]
assign me this issue, please
