### ISSUE TITLE
Check if an Integer is Divisible By Five

### ISSUE THREAD

**Issue by yosuaricky** [Py-Droid/Python-Thunder#164]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement: Create a function that returns True if an integer is evenly divisible by 5, and False otherwise.**
**Problem Link: https://edabit.com/challenge/49pyDP8dE3pJ2dYMW** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by yosuaricky** [comment]
Please assign this to me...

**Comment by Nandita-Gupta14** [comment]
please assign this to me

**Comment by Renu-code** [comment]
please assign it to me

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid Please assign this issue to me.Thanks!

**Comment by tdserapio** [comment]
@aayushi-droid  Please assign this issue to me. Thank you in advanced!
