### ISSUE TITLE
Compare Strings by Count of Characters

### ISSUE THREAD

**Issue by ronika-das** [Py-Droid/Python-Thunder#166]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Compare Strings by Count of Characters
**Problem Link:**  https://edabit.com/challenge/C3N2JEfFQoh4cqQ98

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ronika-das** [comment]
Please assign this to me

**Comment by sah16** [comment]
I would love to work on it.  Please assign

**Comment by dhavalmaniyar** [comment]
@ronika-das  please assign it to me.
