### ISSUE TITLE
Count Ones in Binary Representation of Integer

### ISSUE THREAD

**Issue by nikhilrevankar98** [Py-Droid/Python-Thunder#168]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Count the amount of ones in the binary representation of an integer. So for example, since 12 is '1100' in binary, the return value should be 2
**Problem Link:** https://edabit.com/challenge/GbyPdqNnp75Wci7Cn

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by nikhilrevankar98** [comment]
@aayushi-droid can you assign this task to me?

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid Please assign this task to me?Thanks!

**Comment by hamzzy** [comment]
@aayushi-droid  can you assign me the task  done  just to make a pr

**Comment by leelagenny** [comment]
@aayushi-droid I would like to solve this one. please assign the task to me. Thanks.
