### ISSUE TITLE
It's a Meteor!

### ISSUE THREAD

**Issue by tarundhiraj** [Py-Droid/Python-Thunder#169]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
In a video game, a meteor will fall toward the main character's home planet. Given the meteor's trajectory as a string in the form y = mx + b and the character's position as a tuple of (x, y), return True if the meteor will hit the character and False if it will not
**Problem Link:** 
https://edabit.com/challenge/9YfCbQpRPqRLzPCcg

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by tarundhiraj** [comment]
I would like to contribute to this issue. Please assign me to this.

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid Please assign this issue to me.Thanks!

**Comment by hsrambo07** [comment]
I would like to work on this problem, please assign me this
