### ISSUE TITLE
Identity Matrix

### ISSUE THREAD

**Issue by tarundhiraj** [Py-Droid/Python-Thunder#170]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
Create a function that takes an integer n and returns the identity matrix of n x n dimensions. For this challenge, if the integer is negative, return the mirror image of the identity matrix of n x n dimensions.. It does not matter if the mirror image is left-right or top-bottom.

**Problem Link:** 
https://edabit.com/challenge/QN4RMpAnktNvMCWwg

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by tarundhiraj** [comment]
I would like to contribute to this issue. Please assign me to this issue.

**Comment by Aaditya1978** [comment]
I would like to solve this issue. Please assign this issue to me.
