### ISSUE TITLE
Sum of Prime Numbers

### ISSUE THREAD

**Issue by KuruvillaJacob02** [Py-Droid/Python-Thunder#173]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:Create a function that takes a list of numbers and returns the sum of all prime numbers in the list.**
**Problem Link:https://edabit.com/challenge/GAbxxcsKoLGKtwjRB** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by KuruvillaJacob02** [comment]
@aayushi-droid  It would be much appreciated if this task would be assigned to me

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid Please assign this issue to me.Thanks!

**Comment by KuruvillaJacob02** [comment]
> @aayushi-droid Please assign this issue to me.Thanks!

Hi! Actually you should submit your own issue, and then once its assigned you must sumbit the PR.

**Comment by noemi3** [comment]
Hi! I would like to work on this issue. Thanks.

**Comment by Amrita211** [comment]
Hello! I would love to work on this issue. Thanks!
