### ISSUE TITLE
Four Passengers and a Driver

### ISSUE THREAD

**Issue by prathmeshChaudhari05** [Py-Droid/Python-Thunder#174]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement: Four Passengers and a Driver
**Problem Link: https://edabit.com/challenge/T7DpLzEkAkcxKijzR

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by prathmeshChaudhari05** [comment]
please assign this issue to me

**Comment by Brokenpaws004** [comment]
Assign this task to me

**Comment by Sherlock-B221** [comment]
I am willing to work on this , please assign this to me.

**Comment by sah16** [comment]
please assign it to me
