### ISSUE TITLE
Drunken Python

### ISSUE THREAD

**Issue by ghost** [Py-Droid/Python-Thunder#178]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement:Python got drunk and the built-in functions str() and int() are acting odd:
Problem Link:https://edabit.com/challenge/pfn6QRn6eiTHEPpSs

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
Please Please Please assign me this task please

**Comment by iracaballero** [comment]
Could you assing this issue to me please?

**Comment by Moglten** [comment]
could I contribute here, I will give it a try.

**Comment by aayushi-droid** [comment]
#3 Already completed
