### ISSUE TITLE
Python: Number of Squares in an N * N Grid

### ISSUE THREAD

**Issue by jayanthjj** [Py-Droid/Python-Thunder#18]
In Cpp - https://github.com/Py-Droid/Edabit-Solutions/issues/16
Before jumping into Pr first comment for assign.

**Create a function that calculates the number of different squares in an n * n square grid.** :
**https://edabit.com/challenge/ncqFJAp4bBiGwfBcg** : 
**Choose one Category** - Easy
**question category** : Math

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```python
'''
Problem-Task : This program will add two numbers
Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
@aayushi-droid Can I work on it?

**Comment by aayushi-droid** [comment]
- [✓ ]  Tasl Assigned
@jayanthj737

**Comment by jayanthjj** [comment]
#21 @aayushi-droid

**Comment by jayanthjj** [comment]
A quick doubt how to get the PR done in the same issue itself?

**Comment by aayushi-droid** [comment]
Delete .DS_Store as mentiond
- add, commit and push it will get automaticlly to PR

**Comment by jayanthj737** [comment]
Done yeah!
