### ISSUE TITLE
Calculate the Profit

### ISSUE THREAD

**Issue by suparna13** [Py-Droid/Python-Thunder#180]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement:
You work for a manufacturer, and have been asked to calculate the total profit made on the sales of a product. You are given a dictionary containing the cost price per unit (in dollars), sell price per unit (in dollars), and the starting inventory. Return the total profit made, rounded to the nearest dollar.

Problem Link:
https://edabit.com/challenge/YfoKQWNeYETb9PYpw

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by suparna13** [comment]
@aayushi-droid  I would like to contribute to this issue. Please assign it to me.

**Comment by anshik1998** [comment]
@aayushi-droid, Can you please assign this problem statement to me? I have already written the python program to contribute to this problem using the OOPs concept and just waiting to get it assigned to me.

**Comment by iamKaartik** [comment]
I'll be grateful to you if you could assign this task to me.
