### ISSUE TITLE
Phone Letter Combinations

### ISSUE THREAD

**Issue by Ankit1598** [Py-Droid/Python-Thunder#181]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. A mapping of digit to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.
**Problem Link:** https://edabit.com/challenge/xEGFoPmMm28h7HQ7a

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Ankit1598** [comment]
please assign this to me

**Comment by hsrambo07** [comment]
hey can i take up ths issue thanks

**Comment by aayushi-droid** [comment]
#26 Already complete
