### ISSUE TITLE
Concatenating Two Integer Lists

### ISSUE THREAD

**Issue by ronika-das** [Py-Droid/Python-Thunder#182]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Concatenating Two Integer Lists
**Problem Link:**  https://edabit.com/challenge/cCWMeiJCP9Ef8XMq8

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ronika-das** [comment]
please assign this to me

**Comment by himik-nainwal** [comment]
I have completed python recently please assign me.

**Comment by Sherlock-B221** [comment]
Please assign this to me , i am willing to work on this issue.

**Comment by anirudhthakur** [comment]
can i do this

**Comment by himik-nainwal** [comment]
https://github.com/Himith/Python-Thunder/blob/newpro/concatinateTwoIntList.py

#182 done

**Comment by ashvinimore** [comment]
I have better solution . Can I work on that?
Thank You
