### ISSUE TITLE
Check If Lines Are Parallel

### ISSUE THREAD

**Issue by suparna13** [Py-Droid/Python-Thunder#184]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement:
Given two lines, determine whether or not they are parallel.
Lines are represented by a list [a, b, c], which corresponds to the line ax+by=c.

Problem Link:
https://edabit.com/challenge/8rEEHcmq8rRaTksd7

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by suparna13** [comment]
@aayushi-droid I would like to contribute to this issue. Please assign it to me.

**Comment by dhavalmaniyar** [comment]
@aayushi-droid can you please assign this task to me?

**Comment by Aaditya1978** [comment]
I would like to contribute to this issue . Please assign this to me.

**Comment by thinkswell** [comment]
@aayushi-droid   Hi, Can you assign this issue to me, as I have the code ready.
