### ISSUE TITLE
Invert Keys and Values

### ISSUE THREAD

**Issue by sanskarvijpuria** [Py-Droid/Python-Thunder#185]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement: Write a function that inverts the keys and values of a dictionary.**
**Problem Link: https://edabit.com/challenge/Axim3Ld5zu9RFLZKr** 

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by sanskarvijpuria** [comment]
Assign this to me.

**Comment by DevLokCodes** [comment]
Could i get to work on this problem
Thanking you in advance
