### ISSUE TITLE
Rock, Paper, Scissors!

### ISSUE THREAD

**Issue by gokulrajanpillai** [Py-Droid/Python-Thunder#186]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function to simulate the rock, paper, scissors game between Abigail and Benson.
**Problem Link:** https://edabit.com/challenge/p6uXeD7JC7cmxeD2Z

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
Abigail and Benson are playing Rock, Paper, Scissors.

Each game is represented by an array of length 2, where the first element represents what Abigail played and the second element represents what Benson played.

Given a sequence of games, determine who wins the most number of matches. If they tie, output "Tie".

R stands for Rock
P stands for Paper
S stands for Scissors

Examples
calculate_score([["R", "P"], ["R", "S"], ["S", "P"]]) ➞ "Abigail"

# Ben wins the first game (Paper beats Rock).
# Abigail wins the second game (Rock beats Scissors).
# Abigail wins the third game (Scissors beats Paper).
# Abigail wins 2/3.

calculate_score([["R", "R"], ["S", "S"]]) ➞ "Tie"

calculate_score([["S", "R"], ["R", "S"], ["R", "R"]]) ➞ "Tie"

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gokulrajanpillai** [comment]
@aayushi-droid: Please add the label hard and assign this issue to me.
Thanks in advance.

**Comment by DevLokCodes** [comment]
can I work on this problem 
could you assign this problem to me

**Comment by rianrishu** [comment]
Assign me to this task

**Comment by gokulrajanpillai** [comment]
@rianrishu @DevLokCodes This is already solved, I have made a PR for this aswell. Please follow the repo guidelines and make another issue.

**Comment by aayushi-droid** [comment]
Thanks for messaging but priority will give to issue-author(who created the issue)
