### ISSUE TITLE
Return string as an integer

### ISSUE THREAD

**Issue by Neel2904** [Py-Droid/Python-Thunder#188]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes a string and returns it as an integer.
**Problem Link:** https://edabit.com/challenge/GPmoRCZKkyNtoJMcN

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Neel2904** [comment]
I want to work on this.
**Assign me**

**Comment by kubercodes** [comment]
I am searching for projects and issue for my very first hacktoberfest contributions and this looks very perfect for me.... can you please assign it to me

**Comment by khandelwalsarvesh** [comment]
Can you assign this task to me? I worked in Python quite a few times. I can do this task with all necessary guidelines.
Assign Me.

**Comment by Neel2904** [comment]
@sark-2110  do not PR before you assigned on issue. That is opposing the guidelines of the project.

**Comment by aayushi-droid** [comment]
@sark-2110 Invalid PR

**Comment by khandelwalsarvesh** [comment]
Can you assign me this? Thanks.
