### ISSUE TITLE
Alphabet Soup

### ISSUE THREAD

**Issue by Neel2904** [Py-Droid/Python-Thunder#189]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes a string and returns a string with its letters in alphabetical order.
**Problem Link:** https://edabit.com/challenge/4Agr8CTY7x2rAhh5n

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Neel2904** [comment]
I would like to work on this.
Can you **Assign me** @aayushi-droid

**Comment by ashwinvin** [comment]
Hello @Neel2904, Could you be kind enough to _assign me_ this?

**Comment by Neel2904** [comment]
@ashwinvin Sorry, I can't assign anyone. I'm also contributor and only admin can assign for issue.

**Comment by Neel2904** [comment]
@aayushi-droid  Assign me I want to work on this.
