### ISSUE TITLE
Bitwise Operator to Check Odd, Regular Expression to Check Even

### ISSUE THREAD

**Issue by sanskarvijpuria** [Py-Droid/Python-Thunder#191]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement: Create two functions: 

1. The first is is_odd() to check if a given number is odd using a bitwise operator.

2. The second is is_even() to check if a given input is even using regular expressions.**

**Problem Link: https://edabit.com/challenge/QEL3QAY9ZhSkZcEih ** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by sanskarvijpuria** [comment]
Assign me this issue @aayushi-droid

**Comment by thevivekmnair** [comment]
Can i do it . Can u assign it to me

**Comment by aishuo07** [comment]
Can u assign me?
