### ISSUE TITLE
Oddish vs. Evenish

### ISSUE THREAD

**Issue by mdegis** [Py-Droid/Python-Thunder#195]
**Problem statement:**

Create a function that determines whether a number is Oddish or Evenish. A number is Oddish if the sum of all of its digits is odd, and a number is Evenish if the sum of all of its digits is even. If a number is Oddish, return "Oddish". Otherwise, return "Evenish".

For example, oddishOrEvenish(121) should return "Evenish", since 1 + 2 + 1 = 4. oddishOrEvenish(41) should return "Oddish", since 4 + 1 = 5.

**Problem Link:** 
https://edabit.com/challenge/r6TSNwkLZ2DgsoKiH

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

**Comment by mdegis** [comment]
I would like to work on this 🕵️‍♂️

**Comment by somkuwaryash** [comment]
Hey,
       I would like to work on this. Please assign this to me.

**Comment by GnathMath** [comment]
I would like to work on this problem too

**Comment by DhanushNehru** [comment]
Can I work on this using javascript. Please assign to me

**Comment by asiskumarroy** [comment]
please assign me this i would like to work on it

**Comment by abhirambsn** [comment]
I would like to work on this problem, please consider me for assignment on this problem
