### ISSUE TITLE
Return the Sum of Two Numbers

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#2]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes two numbers as arguments and return their sum.
**Problem Link:** https://edabit.com/challenge/rZToTkR5eB9Zn4zLh

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jakansha2001** [comment]
Can you assign me this issue?

**Comment by aayushi-droid** [comment]
- [✔️ ] Task Assigned

**Comment by AdeshChoudhar** [comment]
I would like to work on this.

**Comment by Ayush7-BIT** [comment]
Hey! can i work on this issue...
