### ISSUE TITLE
Factorial of a Number

### ISSUE THREAD

**Issue by 000Nobody** [Py-Droid/Python-Thunder#207]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
Create a function that receives a non-negative integer and returns the factorial of that number.

**Problem Link:** 
https://edabit.com/challenge/PNbsQzmDR3CJ9JHkB

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

**Comment by 000Nobody** [comment]
Can this be assigned to me?

**Comment by ayu16** [comment]
please assign this to me...

**Comment by thevivekmnair** [comment]
Can i do it .
Please assign me

**Comment by Raghibshams456** [comment]
please assign this to me..

**Comment by iriyagupta** [comment]
@000Nobody Hi, can you assign this to me, i have the code ready.

**Comment by 000Nobody** [comment]
made pr #217

**Comment by JoshuaOloton** [comment]
Please assign this to me

**Comment by thinkswell** [comment]
Hey, It would be my pleasure if you assign me this task, as I am already done with the solution just need the assignment to give PR.
Thank You.

**Comment by aishuo07** [comment]
I have ready code please assign to me

**Comment by ghost** [comment]
Hi,
Can I contribute on this?

**Comment by Zaidtech** [comment]
hi!! can I take on this issue?
