### ISSUE TITLE
Caesar's Cipher

### ISSUE THREAD

**Issue by ayanctech** [Py-Droid/Python-Thunder#210]
https://edabit.com/challenge/C45TKLcGxh8dnbgqM
```
Create a function that takes a string s (text to be encrypted) and an integer k (the rotation factor). It should return an encrypted string.
```
Can this be assigned to me
I have solved this question and tried to make it very simple with comments, please have a look and merge!

**Comment by mrselukar** [comment]
I would like to work on this issue.

**Comment by KuruvillaJacob02** [comment]
Hey there, unfortunately a PR has already been submitted for Ceasars Cipher

**Comment by aayushi-droid** [comment]
#144 Duplicate
