### ISSUE TITLE
BalancingScales

### ISSUE THREAD

**Issue by 7vikpeculiar** [Py-Droid/Python-Thunder#215]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Given a list with an odd number of elements, return whether the scale will tip "left" or "right" based on the sum of the numbers. The scale will tip on the direction of the largest total. If both sides are equal, return "balanced".

**Problem Link:**  https://edabit.com/challenge/xPmfKHShmuKL5Qf9u
---

Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by 7vikpeculiar** [comment]
Hi, can I work on this problem . I checked all the problems contributed to, this is a new one

**Comment by Gerald-Izuchukwu** [comment]
Can I be assigned o this?

**Comment by JoshuaOloton** [comment]
Please assign this to me
