### ISSUE TITLE
Encode Morse

### ISSUE THREAD

**Issue by mrselukar** [Py-Droid/Python-Thunder#218]
Encode Morse: Encoding string to morse code

**Problem statement:** Create a function that takes a string as an argument and return a non-encoded, encrypted string.
**Problem Link:** https://edabit.com/challenge/5bYXQfpyoithnQisa

Morse Code is extremely popular, I would like to work on this. 

I have thoroughly checked the PRs, Issues, and the code.
This problem seems to be a new one Issue #199 is solving the [Atbash Cipher](https://edabit.com/challenge/MGALfBAXhXqqdFyqo) problem

**Comment by mrselukar** [comment]
Could you please assign this to me

**Comment by DevLokCodes** [comment]
I would like to work on this problem 
can i get to work on it
