### ISSUE TITLE
The Karaca's Encryption Algorithm

### ISSUE THREAD

**Issue by TEMHITHORPHE** [Py-Droid/Python-Thunder#221]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** 
Make a function that encrypts a given input with these steps:

		Input: "apple"
		Step 1: Reverse the input: "elppa"
		Step 2: Replace all vowels using the following chart:
		a => 0
		e => 1
		i => 2
		o => 2
		u => 3
		# "1lpp0"
		Step 3: Add "aca" to the end of the word: "1lpp0aca"
		Output: "1lpp0aca"
		Examples
		encrypt("banana") ➞ "0n0n0baca"
		encrypt("karaca") ➞ "0c0r0kaca"
		encrypt("burak") ➞ "k0r3baca"
		encrypt("alpaca") ➞ "0c0pl0aca"
		Notes
		All inputs are strings, no uppercases and all output must be strings.

**Problem Link:**  https://edabit.com/challenge/JzBLDzrcGCzDjkk5n

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ x]  Add label for Problem 
- [ x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by TEMHITHORPHE** [comment]
can this be assigned to me please ?

**Comment by siddheshih** [comment]
Could you please assign this task to me?

**Comment by yashqwerty1** [comment]
I will do it.

**Comment by nootz1999** [comment]
can i work on this?

**Comment by TEMHITHORPHE** [comment]
come on!! guys!.... you cant work on it if you aren't assigned to it yet ... the pull request will be rejected!! ... and besides ... i authored the issue and requested for it first ... it's a first come first serve thing guys ... the README says so ...
