### ISSUE TITLE
Numbers to English

### ISSUE THREAD

**Issue by TEMHITHORPHE** [Py-Droid/Python-Thunder#222]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
`Problem statement: Make a function that encrypts a given input with these steps:Write a function that accepts a positive
integer between 0 and 999 inclusive and returns a string representation of that integer written in English.:

	Examples
	num_to_eng(0) ➞ "zero"
	num_to_eng(18) ➞ "eighteen"
	num_to_eng(126) ➞ "one hundred twenty six"
	num_to_eng(909) ➞ "nine hundred nine"
	Notes
	There are no hyphens used (e.g. "thirty five" not "thirty-five").
	The word "and" is not used (e.g. "one hundred one" not "one hundred and one").
`

Problem Link : **https://edabit.com/challenge/mZqMnS3FsL2MPyFMg**

**Problem Link:** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ x]  Add label for Problem 
- [ x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by TEMHITHORPHE** [comment]
can i get assigned to this please ?

**Comment by fredcodee** [comment]
hello, i would love to help solve this issue : https://edabit.com/challenge/mZqMnS3FsL2MPyFMg

**Comment by nootz1999** [comment]
can i do this?

**Comment by Taneesha-creates** [comment]
I'd like to work on this. Please assign it to me!
Thanks in advance :)

**Comment by TEMHITHORPHE** [comment]
come on!! guys!.... you cant work on it if you aren't assigned to it yet ... the pull request will be rejected!! ... and besides ... i authored the issue and requested for it first ... it's a first come first serve thing guys ... the README says so ...

**Comment by DevLokCodes** [comment]
I would like to work on it.
thanks in advance

**Comment by aayushi-droid** [comment]
#247 PR merged
