### ISSUE TITLE
Sum of Prime Numbers

### ISSUE THREAD

**Issue by raniphore** [Py-Droid/Python-Thunder#226]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Create a function that takes a list of numbers and returns the sum of all prime numbers in the list**
**https://edabit.com/challenge/GAbxxcsKoLGKtwjRB** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by raniphore** [comment]
Please assign to me and add the label Hard

**Comment by nootz1999** [comment]
up for it.

**Comment by Asuddle** [comment]
Please assign it to me

**Comment by AmitManna99** [comment]
Please Assign it to me

**Comment by yashqwerty1** [comment]
Will do it.

**Comment by kbhandari98** [comment]
Please assign it to me. I'm new to this.

**Comment by mahesh-kumaran** [comment]
Hey I'm Interested in taking this up !! This would be something great to start my Open Source Journey ! Please assign this to me!

**Comment by iamKaartik** [comment]
I'll be grateful to you, if you could assign this work to me.😊

**Comment by aayushi-droid** [comment]
#173 Duplicate issue and PR
