### ISSUE TITLE
Harshad Number

### ISSUE THREAD

**Issue by TasneemParveen** [Py-Droid/Python-Thunder#229]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
   A number is said to be Harshad if it's exactly divisible by the sum of its digits. Create a function that determines whether a 
   number is a Harshad or not.

**Problem Link:** 
   https://edabit.com/challenge/Rrauvu8afRbjqPM8L

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [X] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [X]  Add label for Problem 
- [X]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by TasneemParveen** [comment]
I would like to work on this so pls assign me to it. I found it under the hard section on edabit so kindly label it hard.

**Comment by DevLokCodes** [comment]
I would like to solve this Problem, Could you assign this problem to me.
