### ISSUE TITLE
Switcharoo

### ISSUE THREAD

**Issue by Diadochokinetic** [Py-Droid/Python-Thunder#231]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes a string and returns a new string with its first and last characters swapped, except under three conditions:

    If the length of the string is less than two, return "Incompatible.".
    If the argument is not a string, return "Incompatible.".
    If the first and last characters are the same, return "Two's a pair.".

**Problem Link: https://edabit.com/challenge/tnKZCAkdnZpiuDiWA** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : Create a function that takes a string and returns a new string with its first and last characters swapped, except under three conditions:

    If the length of the string is less than two, return "Incompatible.".
    If the argument is not a string, return "Incompatible.".
    If the first and last characters are the same, return "Two's a pair.".

    Problem Link : https://edabit.com/challenge/tnKZCAkdnZpiuDiWA
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Diadochokinetic** [comment]
I would like to solve this problem.

**Comment by Aaditya1978** [comment]
I would like to solve this Problem. Please Assign to me.

**Comment by DevLokCodes** [comment]
I would like to work on this Problem. Could you assign this problem to me

**Comment by Diadochokinetic** [comment]
This was Hackotberfest two years ago
