### ISSUE TITLE
War of Numbers

### ISSUE THREAD

**Issue by GSNCodes** [Py-Droid/Python-Thunder#235]
**Problem statement:**
There's a great war between the even and odd numbers. Many numbers already lost their life in this war and it's your task to end this. You have to determine which group is larger: the even, or the odd. The larger group wins.

Create a function that takes an array of integers, sums the even and odd numbers seperately, then returns the larger of the sums minus the smaller.

**Problem Link:** 
https://edabit.com/challenge/Aofd78q72sAtgCyEY
---
- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by GSNCodes** [comment]
@aayushi-droid  Could you assign me this issue, I would like to work on it :)

**Comment by Mikhaylov-yv** [comment]
I created a function
