### ISSUE TITLE
Count Palindrome Numbers in a Range

### ISSUE THREAD

**Issue by mosouab** [Py-Droid/Python-Thunder#239]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement**: Create a function that returns the number of palindrome numbers in a specified range (inclusive).
**Problem Link**: https://edabit.com/challenge/BRoBDeEc2be7wm8BD
**Examples** : 
     countPalindromes(1, 10) ➞ 9

     countPalindromes(555, 556) ➞ 1

     countPalindromes(878, 898) ➞ 3

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Kartik987** [comment]
Hey @sawamoha20 . Can i contribute to this issue?
