### ISSUE TITLE
Count Palindrome Numbers in a Range

### ISSUE THREAD

**Issue by mosouab** [Py-Droid/Python-Thunder#240]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement**: Create a function that returns the number of palindrome numbers in a specified range (inclusive).
**Problem Link**: https://edabit.com/challenge/BRoBDeEc2be7wm8BD
**Examples** : 
     
     countPalindromes(1, 10) ➞ 9

     countPalindromes(555, 556) ➞ 1

     countPalindromes(878, 898) ➞ 3

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jinkya** [comment]
Hello, please assign me.

**Comment by BassCoder2808** [comment]
Hi  I would like you to assign this issue to me.
I have solved the complete problem and here is the output for the same.
PS C:\Users\vedant jolly\Desktop> python .\hacktober.py
1 10
9

PS C:\Users\vedant jolly\Desktop> python .\hacktober.py
878 898
3

I have performed the above code in python,

**Comment by ghost** [comment]
Hello! I would like to have this assigned to me.
