### ISSUE TITLE
Among Us Imposter Formula

### ISSUE THREAD

**Issue by shivanshsinghal107** [Py-Droid/Python-Thunder#249]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that calculates the chance of being an imposter. The formula for the chances of being an imposter is 100 × (i / p) where i is the imposter count and p is the player count. Make sure to round the value to the nearest integer and return the value as a percentage.
**Problem Link:** https://edabit.com/challenge/b36bBpsnzyDbd4mzF

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by shivanshsinghal107** [comment]
I would like to solve this problem, please assign it to me

**Comment by huandrey** [comment]
The "imposter (1, 8)" example of the link provided is returning 13%, wouldn't it be 12%? Or is rounding up intentional?

**Comment by shivanshsinghal107** [comment]
It's weird why python is doing this, but here is something I found
https://stackoverflow.com/questions/51463918/different-results-for-round12-5-on-different-python-versions

**Comment by huandrey** [comment]
that's weird kkkk but good luck :DD

**Comment by kakarot2019** [comment]
It's weird and exciting at the same time. Please assign it to me.I will be more than happy to do this project.

**Comment by shivanshsinghal107** [comment]
Hey @kakarot2019, to contribute to this repository you have to pick one problem from edabit site and then create an issue for solving that problem and ask to be assigned for that, after assigned you can work on your problem and submit the PR.

**Comment by aayushi-droid** [comment]
we are creating and assigning issue to avoid duplicate and spam PR. Thanks for your contributions.
