### ISSUE TITLE
Return Something to Me!

### ISSUE THREAD

**Issue by VectorXz** [Py-Droid/Python-Thunder#251]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Return Something to Me!
**Problem Link:** https://edabit.com/challenge/XXJbGFEkrMWCp8yFn

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by VectorXz** [comment]
I want to solve this problem, please assign this to me. Thank you! :)

**Comment by Chidu2000** [comment]
please assign me the problem , looking forward to work on this

**Comment by DuncanScu** [comment]
Please assign this problem to me, I have a solution ready :)

**Comment by kakarot2019** [comment]
I have solved the problem . Please assign it to me so that i can merge my solution
