### ISSUE TITLE
Convert age to days

### ISSUE THREAD

**Issue by kakarot2019** [Py-Droid/Python-Thunder#255]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
accepts age and returns the number of days
**Problem Link:** 
https://edabit.com/challenge/xbZR26rHMNo32yz35
---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will convert age to days
    Problem Link : https://edabit.com/challenge/xbZR26rHMNo32yz35
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by kakarot2019** [comment]
please assign it to me .I know how to solve it .

**Comment by NitinShaily** [comment]
please assign it to me I can solve this problem

**Comment by AbhishekBhosale46** [comment]
I will solve it immediately please assign it to me.

**Comment by AvinashSubhash** [comment]
Hey, It would be great if you could assign me for this :-) I'll Solve it.

**Comment by aayushi-droid** [comment]
priority to issue creator
