### ISSUE TITLE
Fullname and Email

### ISSUE THREAD

**Issue by huandrey** [Py-Droid/Python-Thunder#257]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create the instance attributes **fullname** and **email** in the **Employee** class. Given a person's first and last names:
- Form the **fullname** by simply joining the first and last name together, separated by a space.
- Form the **email** by joining the **first** and **last name** together with a **"."** in between, and follow it with **_@company.com_** at the end. Make sure the entire email is in **lowercase**.

**Problem Link:** https://edabit.com/challenge/gB7nt6WzZy8TymCah

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by huandrey** [comment]
Hello, I can work on this problem. I checked all the problems contributed, this is for sure is a new one: D

**Comment by PranavAnand587** [comment]
Hello, Can I work on this problem and make a PR?

**Comment by Madhav243** [comment]
Can i work on this and make a PR?

**Comment by ghost** [comment]
Can I work on this?

**Comment by taneemishere** [comment]
Let this assign to me I can do this. Please I'll an entry for the Hacktoberfest!

**Comment by huandrey** [comment]
Hey @everyone, to contribute to this repository you have to pick one problem from https://edabit.com and then create an issue for solving that problem and ask to be assigned for that, after assigned you can work on your problem and submit the PR.

**Comment by sumasreeeduru** [comment]
assign me. I would like to work on it.

**Comment by sourabhraha** [comment]
Hello, this issue looks familiar to me as I have gone through edabit .
Can I work on this problem  ?

**Comment by Kasugoud98** [comment]
Hello  @aayushi-droid  can i work on this problem.

**Comment by rajansh87** [comment]
I too want to work on this.

**Comment by iamkumar-gaurav** [comment]
may I have permission for this? I Solved that one from the https://edabit.com/challenge/

**Comment by amyanne** [comment]
Hey! I can do this! Or another one. Just let me know!

**Comment by manthan2501** [comment]
I would like to work on this problem in python. please assign me.

**Comment by aayushi-droid** [comment]
Thanks all of you for your message. But we can assign the issue to only 1 person and priority will be give to the issue creator.
Feel free to check Edabit.com to find new problem to create new issue and PR. 

Best of Luck | Happy HacktoberFest
