### ISSUE TITLE
Convert to Hex

### ISSUE THREAD

**Issue by vmgmreddy** [Py-Droid/Python-Thunder#258]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement: Create a function that takes a strings characters as ASCII and returns each characters hexadecimal value as a string.
Problem Link: https://edabit.com/challenge/g6yjSfTpDkX2STnSX

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vmgmreddy** [comment]
please assign this task to me!

**Comment by khandelwalsarvesh** [comment]
Can you please assign this task to me?
