### ISSUE TITLE
Phone Letter Combinations

### ISSUE THREAD

**Issue by Jayshah6699** [Py-Droid/Python-Thunder#26]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. 
**Problem Link:** https://edabit.com/challenge/npLurjMJofmFRCJwx

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will generate list of all possible string from phone letter
    Problem Link : https://edabit.com/challenge/npLurjMJofmFRCJwx
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Jayshah6699** [comment]
@aayushi-droid assign me the task

**Comment by aayushi-droid** [comment]
- [x] Assigning task to @Jayshah6699 

Valid pull request for HacktoberFest will count from 1 October

**Comment by Jayshah6699** [comment]
Also, add an expert label.

**Comment by aayushi-droid** [comment]
we have Easy, medium and Hard label in Python-Thunder. hard added

**Comment by Jayshah6699** [comment]
@aayushi-droid I have learned all the things about the issue and pull request. Kindly assign me any 4 problems as 4 tasks I will create all pull request on 1st October together. It's up to you I am able to do the expert problem in 20 to 30 min so feel free to assign up to 20 problems to me.

**Comment by Jayshah6699** [comment]
I will code for all of those 20 problems till 1st October and commit them after creating a pull request on 1st October.

**Comment by Jayshah6699** [comment]
@aayushi-droid I am talking about expert problems only. Thank you.
