### ISSUE TITLE
Fibonacci last 2 digits in constant time complexity

### ISSUE THREAD

**Issue by aishuo07** [Py-Droid/Python-Thunder#267]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** find  last 2 digits of nth Fibonacci number
**Problem Link:** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnFibonacciLast2Digits.py
- [ ] python
- [ ]  program to find last 2 digits of a nth Fibonacci number in constant time
```python
'''
    Probem Task : This program will find last 2 digits of nth Fibonacci number
'''
*/

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by aishuo07** [comment]
Can i work on this issue

**Comment by nadavWeisler** [comment]
Please assign me :)

**Comment by sajeevan16** [comment]
Please assign this problem

**Comment by ghost** [comment]
Hi,Can i work on this??

**Comment by aayushi-droid** [comment]
Closing the issue.
- It doesn't look like a Edabit problem.
- problem link is missing.
