### ISSUE TITLE
Length of a Nested List

### ISSUE THREAD

**Issue by guptadhaval18** [Py-Droid/Python-Thunder#274]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**Python's len() method will return the number of elements in a list. For example, the list below contains 2 elements:
[1, [2, 3]]
2 elements, number 1 and list [2, 3]
Suppose we instead wanted to know the total number of non-nested items in the nested list. In the above case, [1, [2, 3]] contains 3 non-nested items, 1, 2 and 3.
Create a function that returns the total number of non-nested items in a nested list.
**Problem Link:** https://edabit.com/challenge/xmwdk2qwyZEt7ph49

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by guptadhaval18** [comment]
@aayushi-droid Please assign me this task

**Comment by nitish771** [comment]
Should i request for PR.
