### ISSUE TITLE
LCM of Two Numbers

### ISSUE THREAD

**Issue by guptadhaval18** [Py-Droid/Python-Thunder#275]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**Write a function that returns the least common multiple (LCM) of two integers.
    Examples
    lcm(9, 18) ➞ 18
    lcm(8, 5) ➞ 40
    lcm(17, 11) ➞ 187
    Notes
        Both values will be positive.
        The LCM is the smallest integer that is divisible by both numbers such that the remainder is zero.
**Problem Link:** https://edabit.com/challenge/ERmrS3QrK7sEt4PAt

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by guptadhaval18** [comment]
@aayushi-droid please assign me this issue

**Comment by khandelwalsarvesh** [comment]
Can you assign me this problem?
