### ISSUE TITLE
Difference of Max and Min Numbers in List

### ISSUE THREAD

**Issue by VishalAmbavade** [Py-Droid/Python-Thunder#279]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes a list and returns the difference between the biggest and smallest numbers.

**Examples:** difference_max_min([10, 4, 1, 4, -10, -50, 32, 21]) ➞ 82
Smallest number is -50, biggest is 32.

difference_max_min([44, 32, 86, 19]) ➞ 67
Smallest number is 19, biggest is 86.

**Link to problem statement:**https://edabit.com/challenge/XsJLwhAddzbxdQqr4

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ritwiksingh21** [comment]
Hello! I'd like to be assigned to solve this problem.

**Comment by BAGPALLAB7** [comment]
Hey @VishalAmbavade i want to solve this problem pls assign me to solve this problem.

**Comment by Widell79** [comment]
Would like to give it a try..

**Comment by BAGPALLAB7** [comment]
> Would like to give it a try..

Hey @VishalAmbavade I have added this program please review it and merge this. I'm contributing for the very first time in open source and I'm participating first time on Hacktoberfest. Please accept my code.
