### ISSUE TITLE
Convert to Hex

### ISSUE THREAD

**Issue by prakash-naikwadi** [Py-Droid/Python-Thunder#284]
**Problem statement:** Create a function that takes a strings characters as ASCII and returns each characters hexadecimal value as a string.

**Notes**

- Each byte must be seperated by a space.
- All alpha hex characters must be lowercase.

**Problem Link:** https://edabit.com/challenge/jBf8Nq259tBEgsz4X

**Comment by prakash-naikwadi** [comment]
Can I assign to this task?

**Comment by aayushi-droid** [comment]
duplicate of #258
