### ISSUE TITLE
The Fibonacci Number - update Fibbonacci_number.py 

### ISSUE THREAD

**Issue by UjwalKandi** [Py-Droid/Python-Thunder#29]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that, given a number, returns the corresponding Fibonacci number.
**Problem Link:**  https://edabit.com/challenge/8Ko5tPg8Ch5SRCAhA

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by UjwalKandi** [comment]
Can you add me as _Contributor_ so that I can update the current existing **_Fibbonacci_number.py_** which is empty?

**Comment by thakran14** [comment]
kindly assign this issue to me thank you

**Comment by aayushi-droid** [comment]
- [x] Issue assigned to @UjwalKandi

**Comment by HimadriPathak** [comment]
can i do this?

**Comment by AdeshChoudhar** [comment]
I would like to work on this.

**Comment by AVS18** [comment]
Can I do this
It is done
