### ISSUE TITLE
Find the Discount

### ISSUE THREAD

**Issue by Shreejichandra** [Py-Droid/Python-Thunder#292]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:  Create a function that takes two arguments: the final price and the discount as integers and returns the final price after the discount.**
**Problem Link:  https://edabit.com/challenge/L4Hevck84exPwe4wo** 

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by trewest** [comment]
Hi Shreejichandra,

I can help out with this. Do you mind assigning me?

**Comment by Shreejichandra** [comment]
I myself would like to work on this. Please assign it to me @aayushi-droid.

**Comment by hisandeepangara** [comment]
assign to me

**Comment by trewest** [comment]
Apologies @Shreejichandra , I did not read the directions for creating the issue and then having it assigned to you.

All the best!

**Comment by Shreejichandra** [comment]
It's okay @trewest .
