### ISSUE TITLE
Finding Discount in python

### ISSUE THREAD

**Issue by g-jindal2001** [Py-Droid/Python-Thunder#299]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement: Create a function that takes two arguments: the final price and the discount as integers and returns the final price after the discount.

Problem Link: https://edabit.com/challenge/cXnkmRdxqJrwdsP4n

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by satyabansahoo2000** [comment]
@g-jindal2001 assign this to me. I will work on this.

**Comment by g-jindal2001** [comment]
I have already submitted a pull request for this.
Please open an issue first to contribute to this repository
