### ISSUE TITLE
Drunken Python

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#3]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Python got drunk and the built-in functions `str()` and `int()` are acting odd:
**Problem Link:** https://edabit.com/challenge/pfn6QRn6eiTHEPpSs

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by tapish2000** [comment]
Can you assign the issue to me? I would love to do it.

**Comment by aayushi-droid** [comment]
- [✔️ ] Task Assigned @tapish2000
