### ISSUE TITLE
Connecting Words

### ISSUE THREAD

**Issue by Jayshah6699** [Py-Droid/Python-Thunder#30]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that connects each previous word to the next word by the shared letters. Return the resulting string (removing duplicate characters in the overlap) and the minimum number of shared letters across all pairs of strings.
**Problem Link:** https://edabit.com/challenge/qNQkYzY8GpiFMmndh

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : Connecting Words
    Problem Link : https://edabit.com/challenge/qNQkYzY8GpiFMmndh
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Jayshah6699** [comment]
@aayushi-droid add the hard label and assign me the task

**Comment by aayushi-droid** [comment]
- [x] @Jayshah6699 Best of Luck

**Comment by Jayshah6699** [comment]
@aayushi-droid I have completed all of my tasks kindly merge my pull requests

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly merge the pull request

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly add hacktoberfest-accepted tag
