### ISSUE TITLE
Calculate Age In Days

### ISSUE THREAD

**Issue by vyshakhj-v2** [Py-Droid/Python-Thunder#302]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:Create a function that takes the age and return the age in days.**
**Problem Link:https://edabit.com/challenge/bL7hSc6Zh4zZJzGmw** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python

'''

Problem statement: Create a function that takes the age and return the age in days.
Problem Link: https://edabit.com/challenge/bL7hSc6Zh4zZJzGmw

'''


def calcAge(age):
    return age * 365

```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Hinal-Srivastava** [comment]
Hi!
I'd like to do this

**Comment by skhadirahmed** [comment]
Hi @v-j-0 I would like to work on this

**Comment by tianlangwu** [comment]
Hi @v-j-0! would you mind assign this issue to me?

**Comment by xooseph** [comment]
Hi! I would like to do this @v-j-0
