### ISSUE TITLE
Eight Sums Up

### ISSUE THREAD

**Issue by Jayshah6699** [Py-Droid/Python-Thunder#31]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that gets every pair of numbers from an array that sums up to eight and returns it as an array of pairs (pair sorted ascendingly) collated into an object. See the following examples for more details.
**Problem Link:** https://edabit.com/challenge/ZkWSacTDQ65A3gh6j

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : Eight Sums Up
    Problem Link : https://edabit.com/challenge/ZkWSacTDQ65A3gh6j
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by aayushi-droid** [comment]
- [x] issue assigned to @Jayshah6699

**Comment by Jayshah6699** [comment]
aayushi-droid assigned Jayshah6699
 issue assigned to @Jayshah6699
@aayushi-droid what is the difference between these two?

**Comment by aayushi-droid** [comment]
@Jayshah6699 You have already assigned lot of issue already

**Comment by Jayshah6699** [comment]
there are only three and hacktoberfest needs 4 right?
And I am creating those issues which I have solved.

**Comment by Jayshah6699** [comment]
@aayushi-droid all tasks assigned to me has been accomplished

**Comment by aayushi-droid** [comment]
@Jayshah6699 That's good

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly add the hacktoberfest-comleted label
