### ISSUE TITLE
Concatenating Two Integer Lists

### ISSUE THREAD

**Issue by nootz1999** [Py-Droid/Python-Thunder#311]
Before jumping into Pr first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function to concatenate two integer lists.
**Problem Link:** https://edabit.com/challenge/cCWMeiJCP9Ef8XMq8

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x]   fileName format should be in camelcase
        example- returnTheNextNumber.py   
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
        example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by nootz1999** [comment]
@aayushi-droid  please assign this to me.

**Comment by ilmiye** [comment]
I would like to work on this! can you assign this to me ?

**Comment by lusifer65** [comment]
sir, can you assign to me.

**Comment by nootz1999** [comment]
guys this issue is already assigned to me. And i have already submitted the solution/PR.

If you want to contribute 
1: Go to edabit.com
2: Choose the problem you want to work on and make an issue on that problem.
3: **Wait for the (owner of this repo)aayushi-droid to assign you that issue/problem**.
4: After you get assigned, now make a Pull Request on that issue.
