### ISSUE TITLE
Fit the Pattern

### ISSUE THREAD

**Issue by Jayshah6699** [Py-Droid/Python-Thunder#32]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**Create a function that checks if the sub-arrays in an array adhere to the specified pattern.
**Problem Link:** https://edabit.com/challenge/oXWwHkutPD5Aer6Db

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : Fit the Pattern
    Problem Link : https://edabit.com/challenge/oXWwHkutPD5Aer6Db
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by aayushi-droid** [comment]
Thanks for creating new issue @Jayshah6699

**Comment by Jayshah6699** [comment]
Welcome @aayushi-droid add hard label and assign it to me

**Comment by AmeyaJain-25** [comment]
Hi @Jayshah6699 ,
I would like to work on this.
Please assign me this issue
