### ISSUE TITLE
Convert Hours and Minutes into Seconds

### ISSUE THREAD

**Issue by akanksha470** [Py-Droid/Python-Thunder#320]
Before jumping into Pr first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that takes two integers (hours, minutes), converts them to seconds, and adds them.
**Problem Link:** https://edabit.com/challenge/PjcKZRx8YE5KzRN63

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by akanksha470** [comment]
Please assign it to me.

**Comment by TheSussex** [comment]
Can this be assigned to me? @akanksha470

**Comment by akanksha470** [comment]
Actually I wanted to work on it.
 @aayushi-droid  Please assign it to me.

**Comment by lusifer65** [comment]
sir, can you assign to me

**Comment by aayushi-droid** [comment]
@akanksha470 It's a duplicate issue #134
