### ISSUE TITLE
Harshad Number

### ISSUE THREAD

**Issue by 7vikpeculiar** [Py-Droid/Python-Thunder#327]
Before jumping into Pr first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:** A number is said to be Harshad if it's exactly divisible by the sum of its digits. Create a function that determines whether a number is a Harshad or not.
**Problem Link:**  https://edabit.com/challenge/eADRy5SA5QbasA3Qt

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [ ] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by 7vikpeculiar** [comment]
Can I work on this problem ?

**Comment by ayoolafelix** [comment]
Hey @7vikpeculiar, I would love to perform this task in Python, can you assign this to me?

**Comment by 7vikpeculiar** [comment]
Hi @ayoolafelix, you can choose any problem from edabit ... I don't have the authority to assign the issue

**Comment by ayoolafelix** [comment]
You mean, I can solve the problem, I don't need to be assigned?

**Comment by 7vikpeculiar** [comment]
No.... I put this issue because, I wanted to work on this problem... The admin will assign the problem. You can choose any problem you want to solve and put up a similar issue to solve it. Check out the contribution guidelines

**Comment by ayoolafelix** [comment]
Alright, thanks
