### ISSUE TITLE
Water Jug Problem

### ISSUE THREAD

**Issue by Jayshah6699** [Py-Droid/Python-Thunder#33]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**Given a set of 3 jugs of water that have capacities of a, b, and c liters, find the minimum number of operations performed before each jug has x, y, and z liters. Only jug C will start completely filled.

An operation is any of the following: A jug is emptied, a jug is filled, or water is poured from one jug to another until one of the jugs is either empty or full.

For example, jugs A, B, and C with capacities of 3, 5, and 8, where jugs A and B start empty and C has the full 8, require 2 operations to reach the state of 0, 3, and 5 liters in the jugs.

Create a function that, given an array of jug capacities [A, B, C] and an goal state array [x, y, z], returns the minimum number of operations needed to reach the goal state. If the inputs are invalid or there is no solution, return "No solution."
**Problem Link:** https://edabit.com/challenge/BMujCYCkTowit85Wq

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will solve the classic water Jug Problem
    Problem Link : https://edabit.com/challenge/BMujCYCkTowit85Wq
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
Hey @Jayshah6699  I have worked on this statement in 3rd Semester in C++ I just how transform language and I think I will for Hacktober  Fest! Please assign me!

**Comment by aayushi-droid** [comment]
- [x] Assigning @smeet-kothari .

**Comment by Jayshah6699** [comment]
@aayushi-droid add also hard label

**Comment by Jayshah6699** [comment]
Happy coding @smeet-kothari
