### ISSUE TITLE
simple OOP Calculator

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#333]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create methods for the Calculator class that can do the following:

- Add two numbers.
- Subtract two numbers.
- Multiply two numbers.
- Divide two numbers.

**Problem Link:** https://edabit.com/challenge/ta8GBizBNbRGo5iC6

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by RazCrimson** [comment]
Can I try this?

**Comment by RazCrimson** [comment]
@aayushi-droid This seems to be a copy of Issue https://github.com/codeDroid1/Python-Thunder/issues/305. But the original assignee didnt have PRs, so its fine for me to try?

**Comment by RazCrimson** [comment]
It never got assigned. You don't submit a PR before it gets assigned.Please read the guidelines

**Comment by aayushi-droid** [comment]
duplicate of #305.

**Comment by aayushi-droid** [comment]
Thanks @RazCrimson3 
Check the Edabit.com and find a new question to create a new Issue and PR.

**Comment by RazCrimson** [comment]
Ok, got it.
