### ISSUE TITLE
Longest Alternative Substring

### ISSUE THREAD

**Issue by Jayshah6699** [Py-Droid/Python-Thunder#34]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Given a string of digits, return the longest substring with alternating odd/even or even/odd digits. If two or more substrings have the same length, return the substring that occurs first.
**Problem Link:** https://edabit.com/challenge/RB6iWFrCd6rXWH3vi

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will find longest substring with alternating odd/even or even/odd digits
    Problem Link : https://edabit.com/challenge/RB6iWFrCd6rXWH3vi
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Halix267** [comment]
I want To work on this issue .Can u assign it to me.

**Comment by amitsaini4556** [comment]
I would like to work on this issue. Please assign it to me.
Thank You.

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly assign the task to someone and add hard label

**Comment by aayushi-droid** [comment]
- [x] @amitsaini4556 assigned

**Comment by amitsaini4556** [comment]
Thanks @aayushi-droid
