### ISSUE TITLE
[Problem] [Python] [Hacktoberfest] QuadraticEquation

### ISSUE THREAD

**Issue by devaslooper** [Py-Droid/Python-Thunder#348]
Problem statement: Create a function to find only the root value of x in any quadratic equation ax^2 + bx + c. The function will take three arguments:
- a as the coefficient of x^2
- b as the coefficient of x
- c as the constant term
Problem Link: https://edabit.com/challenge/MDWFcHCTiJfHmwTFx

- [x]  fileName format should be in camelcase
example- returnTheNextNumber.py
- [x] Add label for Problem
- [x]  In file there should be problem statement and link to problem
example -
[Read before making PR - How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)

**Comment by kazoni** [comment]
I'd be happy to take this one on.

**Comment by devaslooper** [comment]
@aayushi-droid Please assign
