### ISSUE TITLE
Simple OOP Calculator

### ISSUE THREAD

**Issue by vivekkj123** [Py-Droid/Python-Thunder#35]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** 

Create methods for the Calculator class that can do the following:

    Add two numbers.
    Subtract two numbers.
    Multiply two numbers.
    Divide two numbers.

Examples

calculator = Calculator()

calculator.add(10, 5) ➞ 15

calculator.subtract(10, 5) ➞ 5

calculator.multiply(10, 5) ➞ 50

calculator.divide(10, 5) ➞ 2

Notes

    The methods should return the result of the calculation.
**Problem Link:**  https://edabit.com/challenge/ta8GBizBNbRGo5iC6

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vivekkj123** [comment]
@aayushi-droid  Please assign this issue to me.... :),
Thanks

**Comment by kamil200** [comment]
Hi,
I would love to work on this issue as my first contribution.
I am new to github but not python.

Can i work on it?

**Comment by satwik-chowdary** [comment]
Assign me to this

**Comment by aayushi-droid** [comment]
#15 duplicate issue, closing now
