### ISSUE TITLE
[Problem] [Python] [Hacktoberfest] Geometry 1: Length of Line Segment

### ISSUE THREAD

**Issue by devaslooper** [Py-Droid/Python-Thunder#350]
Problem statement: Write a function that takes coordinates of two points on a two-dimensional plane and returns the length of the line segment connecting those two points.
Problem Link: https://edabit.com/challenge/3Ekam9jvbNKHDtx4K

- [x]  fileName format should be in camelcase
example- returnTheNextNumber.py
- [x] Add label for Problem
- [x]  In file there should be problem statement and link to problem
example -
[Read before making PR - How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)

**Comment by devaslooper** [comment]
@aayushi-droid Sorry, I accidently stacked the commits in a single pull request while creating a pull request from my fork
PR: #349

**Comment by kazoni** [comment]
I'll take this one on.

**Comment by devaslooper** [comment]
@aayushi-droid Please assign
