### ISSUE TITLE
Anyone else, who is unable to clone this repo (in Windows 10)

### ISSUE THREAD

**Issue by nootz1999** [Py-Droid/Python-Thunder#352]
I was unable to clone this repo, it was throwing an error, I am using windows 10.

**there is this file with  special character(*) in it's name in Solutions folder** 

 

i think this file is creating the problem in cloning(due to it's name), cause after changing the name of this file in forked repo...i was able to clone, from forked repo,( not from the original repo).

can anyone please check this thing... [@aayushi-droid Please look into the issue]
cause if this is true then the name of the file needs to be changed.

Thanks! 
 

![b](https://user-images.githubusercontent.com/35323118/96906769-ecd6c180-14b7-11eb-9a26-eee285ecc399.png)

![b_one](https://user-images.githubusercontent.com/35323118/96906775-eea08500-14b7-11eb-8ff4-5387c71408c1.png)

**Comment by aayushi-droid** [comment]
Thanks for pointing out the issue. Windows doesn't allow some special characters in the file name.

**Comment by nootz1999** [comment]
#353
