### ISSUE TITLE
Volume of a Spherical Shell

### ISSUE THREAD

**Issue by vivekkj123** [Py-Droid/Python-Thunder#36]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
The volume of a spherical shell is the difference between the enclosed volume of the outer sphere and the enclosed volume of the inner sphere:

Volume of Inner Sphere Formula

Create a function that takes r1 and r2 as arguments and returns the volume of a spherical shell rounded to the nearest thousandth.

![](https://edabit-challenges.s3.amazonaws.com/kugelschale.png)
Examples

vol_shell(3, 3) ➞ 0

vol_shell(7, 2) ➞ 1403.245

vol_shell(3, 800) ➞ 2144660471.753

Notes

The inputs are always positive numbers. r1 could be the inner radius or the outer radius, don't return a negative number.
**Problem Link:**  https://edabit.com/challenge/iBqJcagS56wmDpe4x

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vivekkj123** [comment]
@aayushi-droid  Assign this issue to me...

**Comment by AdeshChoudhar** [comment]
I would like to work on this.

**Comment by Avhijit-Nair** [comment]
Please assign this issue to me.

**Comment by raph941** [comment]
i would love to work on this project

**Comment by aawizard** [comment]
I would like to solve this problem

**Comment by Gautam-virmani** [comment]
I would love to work on this and I am good at problem-solving. I also have a gold badge on hackerrank in problem-solving. You can check that out here:https://www.hackerrank.com/Gvirmani1505.

**Comment by ghost** [comment]
Sir submitted a pull request a spherical 100% working it doesn't return a negative value please kindly consider it

**Comment by vivekkj123** [comment]
@aayushi-droid Please review and the merge the Pull request #148 ,

Thanks,

VIVEK K J
