### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by kaushalendra-pandey** [Py-Droid/Python-Thunder#360]
Before jumping into Pr first comment for assign. All Problem from Edabit. Link is mandatory to add

Problem Statement : Write a program to solve a Sudoku puzzle by filling the empty cells.

A sudoku solution must satisfy all of the following rules:

Each of the digits 1-9 must occur exactly once in each row.
Each of the digits 1-9 must occur exactly once in each column.
Each of the digits 1-9 must occur exactly once in each of the 9 3x3 sub-boxes of the grid.
The '.' character indicates empty cells.

Problem Link : 
https://leetcode.com/problems/sudoku-solver/

**Comment by jsilva234** [comment]
I would like to be assign this issue :)

**Comment by nitish771** [comment]
Can multiple persons be assigned on same problem. If yes, I would love to.
