### ISSUE TITLE
Complex Numbers

### ISSUE THREAD

**Issue by kushalbargoti** [Py-Droid/Python-Thunder#40]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that takes a string "a + bi" and returns a tuple (a, b).
**Problem Link:** https://edabit.com/challenge/oFNJeSzzcTgMwLFy5

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by kushalbargoti** [comment]
@aayushi-droid  Please Assign this issue to me... I will do my best .. :)
Add Hard label also.

**Comment by AVS18** [comment]
I can help you to get it done

**Comment by kushalbargoti** [comment]
Hey @AVS18 you can choose another problem from edabit then create an issue and get it assigned and work on it.

**Comment by AVS18** [comment]
Like I am about to submit the problem. Ok I will submit more

**Comment by meta-crusher** [comment]
can u assign this question to me

**Comment by aawizard** [comment]
Please assign me this issue

**Comment by Neel2904** [comment]
I would work on this. Assign me

**Comment by amitagarwalaa57** [comment]
please assign me

**Comment by alokgoldy** [comment]
assign me

**Comment by tusshar17** [comment]
Please assign me for this.

**Comment by vittesha** [comment]
Please assign this problem to me

**Comment by KishanKartha** [comment]
hey I can help, Please assign

**Comment by DipanshuShukla** [comment]
I would be happy to do this. Please assign.

**Comment by GnathMath** [comment]
I request you to assign me the problem on converting a string "a+bi" into a tuple (a,b), where a and b are integers using python.

**Comment by abhirambsn** [comment]
I request you to assign me the problem on converting a string "a+bi" into a tuple (a,b), where a and b are integers using python,
I have the code ready just the formatting as per the above guidelines is needed

**Comment by abhirambsn** [comment]
> I request you to assign me the problem on converting a string "a+bi" into a tuple (a,b), where a and b are integers using python,
> I have the code ready just the formatting as per the above guidelines is needed

I have also done the formatting

**Comment by kushalbargoti** [comment]
@abhirambsn @GnathMath Kindly don't spam here, you can choose another problem from edabit then create an issue and get it assigned and work on it.
So everyone stop spamming here, this issue is already assigned.

**Comment by sb19** [comment]
please Assign me , i will complete this task .

**Comment by kushalbargoti** [comment]
@aayushi-droid  Done ✅
