### ISSUE TITLE
Find the Primorial

### ISSUE THREAD

**Issue by kushalbargoti** [Py-Droid/Python-Thunder#42]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** A Primorial is a product of the first n prime numbers (e.g. 2 x 3 x 5 = 30). 2, 3, 5, 7, 11, 13 are prime numbers. If n was 3, you'd multiply 2 x 3 x 5 = 30 or Primorial = 30.
Create a function that returns the Primorial of a number.
**Problem Link:** https://edabit.com/challenge/fRjfrCYXWJAaQqFXF

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by kushalbargoti** [comment]
@aayushi-droid  Please Assign this issue to me... I will do my best .. :)
Add Hard label also.

**Comment by jinicode** [comment]
I would love to work on this.

**Comment by Shivamishra21** [comment]
I would like to work on this.

**Comment by Abhishek4uh** [comment]
hey! pls, assign to me. I would love to work on this.

**Comment by Deephacks619** [comment]
I wanna work on this code generation. Please assign to me

**Comment by Gautam-virmani** [comment]
I would love to work on this and I am good at problem-solving. I have a gold badge on hackerrank in problem-solving. You can check that out here:https://www.hackerrank.com/Gvirmani1505.

**Comment by aawizard** [comment]
Can I work on this problem?

**Comment by Ansh04122001** [comment]
Can I work on this problem?

**Comment by Tushar-dev-des** [comment]
I will solve this. Over and Out!

**Comment by AayushCodes** [comment]
Please assign. I want to solve this :)

**Comment by Cybersoft82** [comment]
This is very easy question can i try ?Please assign me

**Comment by Pandanoxes** [comment]
Hi, can I be assigned? I want to contribute, it would be my first time contributing to a project.

**Comment by emilkovacev** [comment]
Can I work on this problem? Thank you!

**Comment by sreekesari-vangeepuram** [comment]
Assign me the task!
I have completed this challenge. 
Waiting for assignment!

**Comment by Gautam-virmani** [comment]
Thank you so much for the opportunity . I did it and now you can merge it ,if you want anything please inform me

**Comment by sreekesari-vangeepuram** [comment]
Can you please guide me how to submit a pull request.

Like the steps to make it.
Should I clone your repo and merge it with my code attached?
