### ISSUE TITLE
A Circle and Two Squares

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#5]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Imagine a circle and two squares: a smaller and a bigger one. For the smaller one, the circle is a circumcircle and for the bigger one, an incircle.
![](https://edabit-challenges.s3.amazonaws.com/scale.png)
Create a function, that takes an integer (radius of the circle) and returns the difference of the areas of the two squares.

**Problem Link:** https://edabit.com/challenge/NNhkGocuPMcryW7GP
---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by aswarth123** [comment]
I will be happy to resolve this issues so can you assign it to me?

**Comment by aayushi-droid** [comment]
- [✔️ ] Task Assigned @aswarth123
