### ISSUE TITLE
A Circle and Two Squares

### ISSUE THREAD

**Issue by malhotra-paritosh** [Py-Droid/Python-Thunder#51]
Before jumping into PR, first comment for assignment of the Problem.
All Problems are from Edabit. Link is mandatory to add

**Problem statement: Imagine a circle and two squares: a smaller and a bigger one. For the smaller one, the circle is a circumcircle and for the bigger one, an incircle. Create a function, that takes an integer (radius of the circle) and returns the difference of the areas of the two squares.**

**Problem Link: https://edabit.com/challenge/NNhkGocuPMcryW7GP** 

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by malhotra-paritosh** [comment]
@aayushi-droid Kindly assign this issue to me, I'd love to work on it! 😄

**Comment by AdityaPunetha** [comment]
please assign me this issue

**Comment by Jaideep07** [comment]
I would like to work on this

**Comment by anubhav-08** [comment]
I would like to solve this problem. Please assign it to me

**Comment by anomius** [comment]
Hey can I solve this problem, this would be a oneliner

**Comment by khush31** [comment]
Can work on this issue?

**Comment by Neel2904** [comment]
Can I work on this?

**Comment by aayushi-droid** [comment]
question already solved
