### ISSUE TITLE
Return Areas

### ISSUE THREAD

**Issue by AVS18** [Py-Droid/Python-Thunder#54]
**Problem statement:** We need to find the area difference between the squares where for one square circle is a circumcircle and the other one is incircle
**Problem Link:** https://edabit.com/challenge/NNhkGocuPMcryW7GP

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by AVS18** [comment]
Hi, I found the solution, can you assign that problem to me.

**Comment by AdityaPunetha** [comment]
can you assign me this problem

**Comment by aawizard** [comment]
Can you assign this problem to me?

**Comment by Gautam-virmani** [comment]
I would love to work on this and I am good at problem-solving. Ialso have a gold badge on hackerrank in problem-solving. You can check that out here:https://www.hackerrank.com/Gvirmani1505.

**Comment by Neel2904** [comment]
I would like to work on this problem. please assign it to me.

**Comment by Neel2904** [comment]
Okay @AVS18. you got wrong here. This problem issue is already created in issue #51.

**Comment by AVS18** [comment]
Oops! I thought it was not there. I pulled the code also for the issue but it was not committed to master branch

**Comment by Neel2904** [comment]
@AVS18  That's completely okay. Go for more problems

**Comment by amitagarwalaa57** [comment]
assign to me
