### ISSUE TITLE
Convert Minutes into Seconds

### ISSUE THREAD

**Issue by kokoedwin** [Py-Droid/Python-Thunder#56]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that takes an integer minutes and converts it to seconds.
**Problem Link:** https://edabit.com/challenge/FQyaaJx7orS7tiwz8 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by LagrangianLad** [comment]
I will do it

**Comment by kokoedwin** [comment]
Bro, you need to open https://edabit.com/challenges , find problem that you want to solve, and submit an issues

**Comment by subhanshu2** [comment]
I will do it

**Comment by ShravyaMallya** [comment]
I will do it. Please assign it to me.

**Comment by anomius** [comment]
Hey can I solve this problem, this would be a oneliner

**Comment by aawizard** [comment]
Can I solve it?

**Comment by kokoedwin** [comment]
Please assign this to me, I am the one who create this issues

**Comment by nimendrak** [comment]
I'd like to solve this..

**Comment by azizamurod** [comment]
Hello, I will be very happy to solve this, actually I have solved. Please assign me

**Comment by amitagarwalaa57** [comment]
please assign me

**Comment by krishita30j** [comment]
Can you please assign this issue to me?

**Comment by Kishan-Sahu** [comment]
can you assign this work to me.

**Comment by aayushi-droid** [comment]
@kokoedwin No PR in 11 Days. Assigning to someone else
