### ISSUE TITLE
Return the Sum of Two Numbers

### ISSUE THREAD

**Issue by subhanshu2** [Py-Droid/Python-Thunder#58]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement: Create a function that takes two numbers as arguments and return their sum.
Problem Link: https://edabit.com/challenge/3LpBLgNRyaHMvNb4j

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by anomius** [comment]
Hey can I solve this problem, this would be a oneliner

**Comment by aawizard** [comment]
Can I solve it?

**Comment by Mrinalini99** [comment]
Hey ! Can I solve it?

**Comment by Codedude1** [comment]
I wanna work on this!
