### ISSUE TITLE
Factorial of a Number

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#6]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that receives a non-negative integer and returns the factorial of that number.
**Problem Link:** https://edabit.com/challenge/PNbsQzmDR3CJ9JHkB

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jakansha2001** [comment]
Can i work on this issue?

**Comment by aayushi-droid** [comment]
- [ ✔️] task assigned

@jakansha2001

**Comment by HimadriPathak** [comment]
can i do this

**Comment by AmeyaJain-25** [comment]
Hello @aayushi-droid ,
Can I work on this.
Please assign me the task

**Comment by AdeshChoudhar** [comment]
I would like to work on this.

**Comment by Ayomal98** [comment]
Can I work on this

**Comment by Deephacks619** [comment]
I wanna work on this problem. Please assign me the task.

**Comment by rajat1401** [comment]
Hi @aayushi-droid please assign this to me. 
I have made the [PR](https://github.com/Py-Droid/Python-Thunder/pull/89) for this. Please review it.

**Comment by Deephacks619** [comment]
Hloo @aayushi-droid . I have made PR for this Issue. Please Review it.

**Comment by cryp73r** [comment]
Please review #67 as an efficient program for Factorial of a Number.
