### ISSUE TITLE
Find the area

### ISSUE THREAD

**Issue by Neel2904** [Py-Droid/Python-Thunder#66]
Before jumping into PR first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that takes the base and height of a triangle and return its area.
**Problem Link:** https://edabit.com/challenge/3CaszbdZYGN4otQD8

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] fileName format should be in camel-case
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Neel2904** [comment]
I would like to work on this. 
**Assign me**

**Comment by codetravellearn** [comment]
I WOULD LIKE TO CONTRIBUTE'

**Comment by deecoders** [comment]
I would like to work on this.
Assign me

**Comment by amitagarwalaa57** [comment]
assign me

**Comment by Deephacks619** [comment]
I wanna work on this. Please assign to me.

**Comment by Neel2904** [comment]
@aayushi-droid can you just assign so that I can work on this.
