### ISSUE TITLE
 Maximum Edge of a Triangle

### ISSUE THREAD

**Issue by Neel2904** [Py-Droid/Python-Thunder#69]
Before jumping into PR first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:**  Create a function that finds the maximum range of a triangle's third edge, where the side lengths are all integers.
**Problem Link:** https://edabit.com/challenge/Zerwo2AENbvRZTe83

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] File-Name format should be in camel-case
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Neel2904** [comment]
I want to work on this. 
**Assign me**

**Comment by Ayomal98** [comment]
Can you assign me on this

**Comment by aayushi-droid** [comment]
assinged @palakgautam136
