### ISSUE TITLE
Friday the 13th

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#7]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Given the month and year as numbers, return whether that month contains a Friday 13th.
**Problem Link:** https://edabit.com/challenge/Xkc2iAjwCap2z9N5D

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gokulrajanpillai** [comment]
Pleaes assign me for this.

**Comment by meta-crusher** [comment]
can u assign this problem to me.

**Comment by aayushi-droid** [comment]
- [x] Task assigning to @VaderX 
Best of Luck

**Comment by AdeshChoudhar** [comment]
I would like to work on this.
