### ISSUE TITLE
The Farm Problem

### ISSUE THREAD

**Issue by Neel2904** [Py-Droid/Python-Thunder#70]
Before jumping into PR first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:** A farmer is asking you to tell him how many legs can be counted among all his animals. The farmer breeds three species.
**Problem Link:** https://edabit.com/challenge/QzXtDnSZL6y4ZcEvT

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] File-Name format should be in camel-case
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Neel2904** [comment]
I can work on this.
**Assign me**

**Comment by ghost** [comment]
Hello, I'd like to have this assigned. 
Thanks in advance!
