### ISSUE TITLE
Recursion: Sum

### ISSUE THREAD

**Issue by Neel2904** [Py-Droid/Python-Thunder#71]
Before jumping into PR first comment for assign. All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that finds the sum of the first n natural numbers. Make your function recursive.

**Problem Link:** https://edabit.com/challenge/si2H6WC5YX99cn6LQ

---
Before submitting a PR please Check some details. Check Edabit for problem task

- [x] File-Name format should be in camel-case
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Neel2904** [comment]
I can solve this. 
**Assign me**

**Comment by tanishqj2005** [comment]
can i take it up?

**Comment by deecoders** [comment]
Can I take this up @Neel2904 ?

**Comment by RitikaAg** [comment]
@Neel2904 can I work on this please,thanks!

**Comment by Priyansh2001here** [comment]
Can i work on this

**Comment by kchatr** [comment]
Hey could I work on this? I love recursion :) @Neel2904

**Comment by somkuwaryash** [comment]
@Neel2904 I would like to work on this. I have already solve this and have prepared a code already.
Would be happy to work on it

**Comment by Neel2904** [comment]
Do not PR before admin assign you for an issue. It's opposing the guidelines for this project. I have created this issue because I want to work on it. You all can also work on problem after creating an issue and ask for assign to project admin.
Thank you

**Comment by Amrita211** [comment]
@Neel2904 I would like to work on this issue, please assign me into it.
Thanks !

**Comment by Priyansh2001here** [comment]
@Neel2904 i have completed my code with docs and typing please let me work on it
