### ISSUE TITLE
if-elif-else Inferno

### ISSUE THREAD

**Issue by amitagarwalaa57** [Py-Droid/Python-Thunder#77]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that returns the boolean True if the given number is zero, the string "positive" if the number is greater than zero or the string "negative" if it's smaller than zero.

**Problem Link:** https://edabit.com/challenge/2TdPmSpLpa8NWh6m9

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by KickItLikeShika** [comment]
Please review the pull request i have just made to continue my work. I really like solving this type of problems.
https://github.com/Py-Droid/Python-Thunder/pull/68

**Comment by Srinjoycode** [comment]
Could I please be assigned this task

**Comment by Gerald-Izuchukwu** [comment]
Can I be assigned to this task?
