### ISSUE TITLE
Combinations

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#8]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes a variable number of arguments, each argument representing the number of items in a group, and returns the number of permutations (combinations) of items that you could get by taking one item from each group.
**Problem Link:** https://edabit.com/challenge/G9QRtAGXb9Cu368Pw

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by tapish2000** [comment]
Can you assign this one to me, please?

**Comment by aayushi-droid** [comment]
- [✓] Task Assigned 

@tapish2000 

Pull request for HacktoberFest will count from 1 october to 31 october

**Comment by tapish2000** [comment]
Yeah, I will create a pull request on 1 October. Can you please keep me assigned for this, I have written the code already.

**Comment by gittygupta** [comment]
please assign this to me. my code is written already
