### ISSUE TITLE
Recursive repetition of string 

### ISSUE THREAD

**Issue by RitikaAg** [Py-Droid/Python-Thunder#82]
Before jumping into PR first comment for assign. All Problem from Edabit. Link is mandatory to add

Problem statement: Write a function that creates a recursive function that takes two parameters and repeats the string n number of times. The first parameter txt is the string to be repeated and the second parameter is the number of times the string is to be repeated.

Problem Link: https://edabit.com/challenge/QKmETue6fMTdcB8Rq

Before submitting a PR please Check some details. Check Edabit for problem task

- [x]  File-Name format should be in camel-case
       example- returnTheNextNumber.py

- [x]  Add label for Problem

- [x]  In file there should be problem statement and link to problem

example -
```
'''
    Problem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```
This repository is valid for HacktoberFest2020

Read before making PR - How to contribute on Github
Good Luck,

**Comment by RitikaAg** [comment]
Please assign this task to me

**Comment by somkuwaryash** [comment]
Please assign this task to me. I would like to work on it.

**Comment by rajat1401** [comment]
Hi @RitikaAg Please assign this issue to me.

**Comment by RitikaAg** [comment]
I've created this issue so I can work on it once it's assigned to me, in keeping with the guidelines

**Comment by aayushi-droid** [comment]
Unassigned Pull Request will be mark as invalid and they will not count for Hacktober.

**Comment by RitikaAg** [comment]
@aayushi-droid I've created the PR for this issue
