### ISSUE TITLE
Return the Next Number from the Integer Passed

### ISSUE THREAD

**Issue by GSNCodes** [Py-Droid/Python-Thunder#86]
**Problem statement:**
Create a function that takes a number as an argument, increments the number by +1 and returns the result.

**Problem Link:** 
https://edabit.com/challenge/KjCS7occ9hfu5snpb
---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by GSNCodes** [comment]
@aayushi-droid  Could you assign me this, I would like to work on it?

**Comment by kchatr** [comment]
Can I be assigned this @GSNCodes ?

**Comment by GSNCodes** [comment]
@kchatr I'm working on this. Sorry, I forgot to mention that

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid  Please assign this task to me.Thanks!

**Comment by rishabh-28** [comment]
Please assign this to me

**Comment by Gerald-Izuchukwu** [comment]
Please assign this to me
