### ISSUE TITLE
Less Than 100?

### ISSUE THREAD

**Issue by shubhamgoel9** [Py-Droid/Python-Thunder#88]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**
**Problem Link:** 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : Given two numbers, return True if the sum of both numbers is less than 100. Otherwise return False.
    Problem Link : https://edabit.com/challenge/pZ3HxBfvejsvkEDo4
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by shubhamgoel9** [comment]
assign me

**Comment by pbisen** [comment]
Could you please assign me. i would love to work on this.

**Comment by sourhub226** [comment]
I would like to work on this.

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid  Please assign this task to me.Thanks!

**Comment by offi-ani** [comment]
Can i take up on this? can you please assign me this.i would love to work on this

**Comment by AayushCodes** [comment]
Please Assign me this. I would love to work on it :)

**Comment by Gerald-Izuchukwu** [comment]
Can I please be assigned to this?

**Comment by Amrita211** [comment]
I would love to work on this. Please assign this task to me.

**Comment by aayushi-droid** [comment]
I didn't receive the PR yet. ANyone else want to create PR.
