### ISSUE TITLE
Pentagonal Number

### ISSUE THREAD

**Issue by aayushi-droid** [Py-Droid/Python-Thunder#9]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Write a function that takes a positive integer and calculates how many dots exist in a pentagonal shape around the center dot on the Nth iteration.

In the image below you can see the first iteration is only a single dot. On the second, there are 6 dots. On the third, there are 16 dots, and on the fourth there are 31 dots.

Return the number of dots that exist in the whole pentagon on the Nth iteration.

**Problem Link:** https://edabit.com/challenge/st8mDxreMcuWxuz8c

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by duarte2025** [comment]
Can i work on this issue?

**Comment by aayushi-droid** [comment]
- [✓]  Task assigned @duarte2025

**Comment by gittygupta** [comment]
please assign this to me

**Comment by Ayush7-BIT** [comment]
Hey i like to work on this issue, if possible assign me this..
