### ISSUE TITLE
Atbash Cipher

### ISSUE THREAD

**Issue by duarte2025** [Py-Droid/Python-Thunder#90]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** The Atbash cipher is an encryption method in which each letter of a word is replaced with its "mirror" letter in the alphabet: A <=> Z; B <=> Y; C <=> X; etc.

Create a function that takes a string and applies the Atbash cipher to it.

**Problem Link:**  https://edabit.com/challenge/MGALfBAXhXqqdFyqo

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by duarte2025** [comment]
Can i work on this issue?

**Comment by ryzbaka** [comment]
I am interested in implementing this function.

**Comment by sanuj96** [comment]
Interested
