### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by infern018** [Py-Droid/Python-Thunder#93]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that converts a date formatted as MM/DD/YYYY to YYYYDDMM.

Examples:
```
format_date("11/12/2019") ➞ "20191211"

format_date("12/31/2019") ➞ "20193112"

format_date("01/15/2019") ➞ "20191501"
```

**Problem Link:** https://edabit.com/challenge/co4nwXSvnCjGEu8vp

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by infern018** [comment]
@aayushi-droid please assign this issue to me...

**Comment by sarthak55k** [comment]
can you assign this to me?

**Comment by Ansh04122001** [comment]
can you assign this to me?

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid Please assign this task to me.Thanks!

**Comment by Gerald-Izuchukwu** [comment]
Can I be assigned to this?

**Comment by iriyagupta** [comment]
Hi I have created a pull request for this
