### ISSUE TITLE
Convert Minutes to Seconds

### ISSUE THREAD

**Issue by pbisen** [Py-Droid/Python-Thunder#94]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**: Write a function that takes an integer minutes and converts it to seconds.
**Problem Link:** https://edabit.com/challenge/FQyaaJx7orS7tiwz8

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by pbisen** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by asaravindkumar** [comment]
I can work on this, if open

**Comment by sanuj96** [comment]
Please assign this to me.

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid Please assign this task to me.
Thanks!

**Comment by somkuwaryash** [comment]
@pbisen assign this task to me

**Comment by Roshanpaswan** [comment]
Please assign. I can solve this problem

**Comment by offi-ani** [comment]
Can i take up on this? can you please assign me this

**Comment by AayushCodes** [comment]
Please Assign me this. I would love to work on it :)

**Comment by aayushi-droid** [comment]
Question is already assigned and solved
