### ISSUE TITLE
Profitable Gamble

### ISSUE THREAD

**Issue by Sankalpagrawal** [Py-Droid/Python-Thunder#96]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** Create a function that takes three arguments prob, prize, pay and returns true if prob * prize > pay; otherwise return false.
**Problem Link:**  https://edabit.com/challenge/ghbHrRnRiDz9fvQNF

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Sankalpagrawal** [comment]
I want to take up this issue

**Comment by RamyaThirumalaisamy** [comment]
@Sankalpagrawal  @aayushi-droid Please assign this task to me.Thanks!

**Comment by Rahul30032** [comment]
@Sankalpagrawal I would like to take up this task, If not assigned to anyone, can u assign it to me?

**Comment by aayushi-droid** [comment]
Duplicate issue and task is already completed.
