### ISSUE TITLE
Difference of Max and Min Numbers in List

### ISSUE THREAD

**Issue by somkuwaryash** [Py-Droid/Python-Thunder#97]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**Create a function that takes a list and returns the difference between the biggest and smallest numbers.
**Problem Link:** https://edabit.com/challenge/XsJLwhAddzbxdQqr4

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by somkuwaryash** [comment]
Please assign this task to me. I would like to work on this.

**Comment by esla-ahme** [comment]
I can do it

**Comment by Roshanpaswan** [comment]
I will definitely work for this. Please assign me

**Comment by Aravindha1234u** [comment]
@somkuwaryash Can you Assign this to me Bro I would love to make this.

**Comment by offi-ani** [comment]
Can i take up on this? can you please assign me this

**Comment by Aditi0707** [comment]
can you assign this issue to me

**Comment by Amrita211** [comment]
can you please give me chance to work on this issue . 
Thanks !

**Comment by AayushCodes** [comment]
Please Assign me this. i would love to work on it :)

**Comment by KerinPithawala** [comment]
Can you assign me this?

**Comment by Gerald-Izuchukwu** [comment]
Can i be assigned to this?

**Comment by nootz1999** [comment]
Love to work on this.
