### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by guptadhaval18** [Py-Droid/Python-Thunder#99]
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement: There are three towers. The objective of the game is to move all the disks over to tower #3, but you can't place a larger disk onto a smaller disk. To play the game or learn more about the Tower of Hanoi, check the Resources tab.
Create a function that takes a number discs as an argument and returns the minimum amount of steps needed to complete the game.
**
**Problem Link:** https://edabit.com/challenge/3ZtykTsx3GSoPHyBb

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Add label for Problem 
- [x]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by saigunavanth** [comment]
I would like to work on this issue using python. @guptadhaval18  assign me

**Comment by Bijay555** [comment]
I have wrote code previously in tower of Hanoi. Please assign to me?

**Comment by snehagupta-4** [comment]
@guptadhaval18 I'd love to work on this issue. Please assign it to me. :')

**Comment by rasmita404** [comment]
@guptadhaval18  I would like to work on this using Python. Please assign me.
